#ifndef _AARCH64_BITS_MAIR_
#define _AARCH64_BITS_MAIR_

#define MAIR_NORMAL_INDEX	0
#define MAIR_NORMAL_FLAGS	0xff
#define MAIR_DEVICE_INDEX	1
#define MAIR_DEVICE_FLAGS	0x00

#define MAIR_VALUE_ENTRY(index, flags)		((flags) << ((index) * 8))
#define MAIR_VALUE		(MAIR_VALUE_ENTRY(MAIR_NORMAL_INDEX, MAIR_NORMAL_FLAGS) | MAIR_VALUE_ENTRY(MAIR_DEVICE_INDEX, MAIR_DEVICE_FLAGS))

#endif /* _AARCH64_BITS_MAIR_ */
